export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEMS = 'ADD_ITEMS';
export const DELETE_ITEMS = 'DELETE_ITEMS';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const SEND_VERIFY_SUCCESS="SEND_VERIFY_SUCCESS"
export const VERIFY_FAIL='VERIFY_FAIL';
export const SEND_OTP_SUCCESS="SEND_OTP_SUCCESS";
export const OTP_FAIL='OTP_FAIL';
export const ADD_TAKEN_APPOINTMENT="ADD_TAKEN_APPOINTMENT";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const UPDATE_DOCTOR_DETAILS='UPDATE_DOCTOR_DETAILS';
export const ADD_DOCTOTR_APPOINTMENT='ADD_DOCTOTR_APPOIMENT';
export const READ_NOTIFICATIONS="READ_NOTIFICATIONS";
////////////////////////////////////////
export const GET_USERS="GET_USERS"
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_ALL_APPOINTMENTS="GET_ALL_APPOINTMENTS"
export const ADD_DOCTOR = 'ADD_DOCTOR';
export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_SINGLE_DOCTOR = 'GET_SINGLE_DOCTOR';
export const DOCTOR_FILTER = 'DOCTOR_FILTER';
export const DOCTOR_REGISTRATION = 'DOCTOR_REGISTRATION';
export const APPROVE_DOCTOR="APPROVE_DOCTOR";
export const ADD_FEEDBACK='ADD_FEEDBACK';
export const ADD_DOCUMENT="ADD_DOCUMENT"
export const ADD_RECOMMENDATION="ADD_RECOMMENDATION";
export const DELETE_USER="DELETE_USER";
export const ADD_RECOMMENDATION_SUCCESS="ADD_RECOMMENDATION_SUCCESS";

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const ADD_UPLOADS = 'ADD_UPLOADS';
export const GET_UPLOADS = 'GET_UPLOADS';

export const ADD_NOTIFICATION="ADD_NOTIFICATION"

export const PICK_APPOINTMENT_DATE = 'PICK_APPOINTMENT_DATE';
export const APPOINTMENT_ERROR = 'APPOINTMENT_ERROR';
export const MAKE_APPOINTMENT = 'MAKE_APPOINTMENT';
export const UPDATE_APPOINTMENT_STATUS = 'UPDATE_APPOINTMENT_STATUS';
export const GET_STATUS_COUNT = 'GET_STATUS_COUNT';
export const CREATE_PRESCRIPTION = 'CREATE_PRESCRIPTION';
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE';
export const UPDATE_APPOINTMENT_PRESCRIPTION ='UPDATE_APPOINTMENT_PRESCRIPTION';

export const IMAGE_CLICKED ='IMAGE_CLICKED';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';

export const GET_PATIENTS = 'GET_PATIENTS';

export const GET_APPOINTMENTS_BY_DATE = 'GET_APPOINTMENTS_BY_DATE';
export const CREATE_REPORT = 'CREATE_REPORT';